# Generated by Django 4.2.7 on 2023-12-07 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=300)),
                ('street', models.CharField(max_length=30)),
                ('number', models.CharField(max_length=10)),
                ('postalcode', models.CharField(max_length=10)),
                ('suburb', models.CharField(max_length=30)),
                ('city', models.CharField(max_length=15)),
                ('state', models.CharField(max_length=15)),
                ('coordinates', models.CharField(max_length=30)),
            ],
        ),
    ]
